import Providers from "./Providers";
import BackToHome from "./components/BackToHome";
import Navbar from "./components/Navbar";
import Theme from "./components/Theme";
import "./globals.css";
import {
  Inter,
  Raleway,
  Playfair_Display,
  Josefin_Sans,
} from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const ralway = Raleway({
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  subsets: ["latin"],
});
const josefin = Josefin_Sans({
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin.className + "bg-white min-h-screen"}>
        <Providers>
          <main className="dark:bg-slate-900 min-h-screen h-full flex flex-col">
            <Navbar />
            <div className="flex-1">{children}</div>
            <footer className="pt-20 pb-5 text-gray-500 text-center text-xs font-mono">
              Next13 | Vercel - Tailwind Css <br />
              Dai Chekkal
            </footer>
          </main>
        </Providers>
      </body>
    </html>
  );
}
